<?php

return [
    'title' => env('APP_NAME', 'API') . ' Documentation',
    'description' => 'API documentation generated by Scribe.',
    'base_url' => env('APP_URL', 'http://localhost'),
    'routes' => [
        [
            'match' => [
                'domains' => ['*'],
                'prefixes' => ['api/v1/*', 'admin/*'],
                'versions' => ['v1'],
            ],
            'include' => [],
            'exclude' => [],
        ],
    ],
    'type' => 'laravel',
    'theme' => 'default',
    'auth' => [
        'enabled' => true,
        'default' => false,
        'in' => 'bearer',
        'name' => 'Authorization',
        'use_value' => env('SCRIBE_AUTH_TOKEN'),
    ],
];

